// Generated by Veect from design.veect.json — do not edit by hand.
// Hand edits flip this file to code-owned and Veect stops regenerating it.

import { Button } from "@/components/ui/button";

export default function Frame1() {
  return (
    <>
      <div className="h-[150px] inline-block mt-[200] bg-[#ff0000] text-[color:var(--color-accent-foreground)]">
        <Button size="default" asChild={false} variant="default">
          Some Button
        </Button>
        <p className="text-[color:white]">Text</p>
      </div>
    </>
  );
}
