// Generated by Veect from design.veect.json — do not edit by hand.
// Hand edits flip this file to code-owned and Veect stops regenerating it.

import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";

export default function Frame1() {
  return (
    <>
      <div className="h-[100vh] flex justify-center items-center">
        <div>
          <Button size="default" asChild={false} variant="default">
            Test button
          </Button>
          <div className="mt-[2em]">
            <Label>Antonija je najbolja</Label>
          </div>
        </div>
      </div>
    </>
  );
}
