// Generated by Veect from design.veect.json — do not edit by hand.
// Hand edits flip this file to code-owned and Veect stops regenerating it.

import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { SelectScrollDownButton } from "@/components/ui/select";

export default function Frame1() {
  return (
    <>
      <Alert variant="destructive">Test</Alert>
      <Button size="lg" asChild={false} variant="default">
        Test button
      </Button>
      <SelectScrollDownButton />
    </>
  );
}
